name: test

on:
  workflow_dispatch:  # Manual trigger

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Output Run ID
        run: |
         echo "Run ID: ${{ github.run_id }}"

      - name: Output Run Number
        run: |
         echo "Run Number: ${{ github.run_number }}"

      - name: Output Run Attempt
        run: |
         echo "Run Attempt: ${{ github.run_attempt }}"
