name: Update Live Track Info Image

on:
  workflow_dispatch:  # Manual trigger
  # schedule:           # Scheduled trigger
  #   - cron: '*/2 * * * *'  # Runs every 2 minutes

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Puppeteer
        run: |
          npm install puppeteer

      - name: Generate SVG Image
        run: |
          node generate-image.js

      - name: Rename image
        run: |
          mv songs-pictures/image.png songs-pictures/image${{ github.run_number }}.png

      - name: Update README.md
        run: |
          # Calculate last run number
          current_run_number=${{ github.run_number }}  # Replace this with the actual value
          last_run_number=$((current_run_number - 1))
          echo "Last run number: $last_run_number"

          awk -v last_run_number="$last_run_number" '{gsub(/!\[\]\(songs-pictures\/image\([0-9]+\)\.png\)/, "![](songs-pictures/image(" last_run_number ").png)")}1' README.md > temp.md && mv temp.md README.md
      
      - name: Commit and push changes
        run: |
          git config --local user.email "eshaniyer@duck.com"
          git config --local user.name "Eshan I."
          git add songs-pictures/image${{ github.run_number }}.png README.md
          git commit -m "Update track info image to image${{ github.run_number }}" || echo "No changes to commit"
          git push
